name: pep8check
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: install and run pycodestyle
        run: |
          pip install pycodestyle
          pycodestyle .
